services:
  - type: web
    name: ecom-sentiment-backend
    runtime: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.api:app
    envVars:
      - key: LLM_MODEL
        value: xiaomi/mimo-v2-flash:free
